[project]
name = "cliggybot"
version = "0.1.0"
description = "A simple chatbot using click for its text-based UI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.0",
    "httpx>=0.28.1",
    "pluggy>=1.6.0",
    "slixmpp>=1.8.6",
]

[project.entry-points."cliggybot_hooks"]
echo_plugin = "cliggybot.plugins.echo"
fav_plugin = "cliggybot.plugins.fav"
hn_plugin = "cliggybot.plugins.hn"
nn_plugin = "cliggybot.plugins.nn"
